// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StarDustTravelAgency.Api.Persistence;

#nullable disable

namespace StarDustTravelAgency.Api.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261006193120_AddUniqueJourneyOccurrence")]
    partial class AddUniqueJourneyOccurrence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StarDustTravelAgency.Api.Domain.Entities.Destination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<decimal>("AverageTemperatureCelsius")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("average_temperature_celsius");

                    b.Property<decimal>("GravityRelativeToEarth")
                        .HasPrecision(6, 3)
                        .HasColumnType("numeric(6,3)")
                        .HasColumnName("gravity_relative_to_earth");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("short_description");

                    b.Property<string>("StarSystem")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("star_system");

                    b.Property<string>("TravelAdvisory")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("travel_advisory");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("destinations", (string)null);
                });

            modelBuilder.Entity("StarDustTravelAgency.Api.Domain.Entities.Journey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ArrivalAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("arrival_at_utc");

                    b.Property<DateTimeOffset>("DepartureAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("departure_at_utc");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("direction");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<Guid>("SpaceshipId")
                        .HasColumnType("uuid")
                        .HasColumnName("spaceship_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid?>("WeeklyScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("weekly_schedule_id");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("Status", "DepartureAtUtc");

                    b.HasIndex("WeeklyScheduleId", "DepartureAtUtc")
                        .IsUnique();

                    b.HasIndex("SpaceshipId", "DepartureAtUtc", "ArrivalAtUtc");

                    b.ToTable("journeys", null, t =>
                        {
                            t.HasCheckConstraint("ck_journeys_arrival_after_departure", "arrival_at_utc > departure_at_utc");

                            t.HasCheckConstraint("ck_journeys_maximum_duration", "arrival_at_utc <= departure_at_utc + INTERVAL '16 hours'");
                        });
                });

            modelBuilder.Entity("StarDustTravelAgency.Api.Domain.Entities.LaunchStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("launch_stations", (string)null);
                });

            modelBuilder.Entity("StarDustTravelAgency.Api.Domain.Entities.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_id");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<Guid>("LaunchStationId")
                        .HasColumnType("uuid")
                        .HasColumnName("launch_station_id");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("LaunchStationId", "DestinationId")
                        .IsUnique();

                    b.ToTable("routes", null, t =>
                        {
                            t.HasCheckConstraint("ck_routes_duration_minutes", "duration_minutes BETWEEN 1 AND 960");
                        });
                });

            modelBuilder.Entity("StarDustTravelAgency.Api.Domain.Entities.Spaceship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("YearBuilt")
                        .HasColumnType("integer")
                        .HasColumnName("year_built");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("spaceships", null, t =>
                        {
                            t.HasCheckConstraint("ck_spaceships_capacity", "capacity > 0");

                            t.HasCheckConstraint("ck_spaceships_year_built", "year_built BETWEEN 2000 AND 9999");
                        });
                });

            modelBuilder.Entity("StarDustTravelAgency.Api.Domain.Entities.WeeklySchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<Guid>("DefaultSpaceshipId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_spaceship_id");

                    b.Property<string>("DepartureDay")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("departure_day");

                    b.Property<TimeOnly>("DepartureTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("departure_time");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("direction");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.HasKey("Id");

                    b.HasIndex("DefaultSpaceshipId");

                    b.HasIndex("RouteId", "Direction", "DepartureDay", "DepartureTime")
                        .IsUnique();

                    b.ToTable("weekly_schedules", (string)null);
                });

            modelBuilder.Entity("StarDustTravelAgency.Api.Domain.Entities.Journey", b =>
                {
                    b.HasOne("StarDustTravelAgency.Api.Domain.Entities.Route", "Route")
                        .WithMany("Journeys")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StarDustTravelAgency.Api.Domain.Entities.Spaceship", "Spaceship")
                        .WithMany("Journeys")
                        .HasForeignKey("SpaceshipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StarDustTravelAgency.Api.Domain.Entities.WeeklySchedule", "WeeklySchedule")
                        .WithMany("Journeys")
                        .HasForeignKey("WeeklyScheduleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Route");

                    b.Navigation("Spaceship");

                    b.Navigation("WeeklySchedule");
                });

            modelBuilder.Entity("StarDustTravelAgency.Api.Domain.Entities.Route", b =>
                {
                    b.HasOne("StarDustTravelAgency.Api.Domain.Entities.Destination", "Destination")
                        .WithMany("Routes")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StarDustTravelAgency.Api.Domain.Entities.LaunchStation", "LaunchStation")
                        .WithMany("Routes")
                        .HasForeignKey("LaunchStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("LaunchStation");
                });

            modelBuilder.Entity("StarDustTravelAgency.Api.Domain.Entities.WeeklySchedule", b =>
                {
                    b.HasOne("StarDustTravelAgency.Api.Domain.Entities.Spaceship", "DefaultSpaceship")
                        .WithMany("WeeklySchedules")
                        .HasForeignKey("DefaultSpaceshipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StarDustTravelAgency.Api.Domain.Entities.Route", "Route")
                        .WithMany("WeeklySchedules")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefaultSpaceship");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("StarDustTravelAgency.Api.Domain.Entities.Destination", b =>
                {
                    b.Navigation("Routes");
                });

            modelBuilder.Entity("StarDustTravelAgency.Api.Domain.Entities.LaunchStation", b =>
                {
                    b.Navigation("Routes");
                });

            modelBuilder.Entity("StarDustTravelAgency.Api.Domain.Entities.Route", b =>
                {
                    b.Navigation("Journeys");

                    b.Navigation("WeeklySchedules");
                });

            modelBuilder.Entity("StarDustTravelAgency.Api.Domain.Entities.Spaceship", b =>
                {
                    b.Navigation("Journeys");

                    b.Navigation("WeeklySchedules");
                });

            modelBuilder.Entity("StarDustTravelAgency.Api.Domain.Entities.WeeklySchedule", b =>
                {
                    b.Navigation("Journeys");
                });
#pragma warning restore 612, 618
        }
    }
}
